version: '3.3'
services:
  client: 
    env_file: ${SHARED_ENV_FILE}
    restart: always
    ports:
      - "${TB_MOBILE_EXTERNAL_PORT}:3000"
    build:
      context: ${TB_MOBILE_CONTEXT}
    stdin_open: true
    tty: true
    container_name: tb-mobile-app  
    command: yarn start
    environment:
      NODE_ENV: development
  web:
    env_file: ${SHARED_ENV_FILE}
    restart: "no"
    build:
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - target: ${TB_API_INTERNAL_PORT}
    volumes:
      - "web:/usr/src/app"
    links:
      - mpower-db
      - tbapp-db
    container_name: tb-api
    stdin_open: true
    # command: /wait && echo $TB_API_INTERNAL_PORT 
    # command: echo ${TB_API_INTERNAL_PORT} && /usr/local/bin/gunicorn -w 2 -b :${TB_API_INTERNAL_PORT} tbapi_app:app
    command: /usr/local/bin/gunicorn --config /gunicorn.conf --log-config /logging.conf --log-file=- -b :5000 tbapi_app:app

    tty: true
    depends_on:
      - mpower-db
      - tbapp-db
    environment:
      GUNICORN_ACCESSLOG: '-'
      GUNICORN_LOG_FILE: '-'
      GUNICORN_LOG_LEVEL: debug
      FLASK_APP: "tbapi_app.py"
      FLASK_DEBUG: 1
      AUTHLIB_INSECURE_TRANSPORT: 'true'
      MODE: 'dev'
    networks:
      - tbapi

  nginx:
    env_file: ${SHARED_ENV_FILE}
    restart: always
    build: ./nginx
    ports:
      - "${TB_API_EXTERNAL_PORT}:80"
    volumes:
      - web:/www/static
    depends_on:
      - web
    networks:
      - tbapi
  mpower-db:
    env_file: ${SHARED_ENV_FILE}
    restart: always
    image: mysql:5.7
    hostname: mpower-db
    volumes:
      - "./db/sql/mpower-db:/docker-entrypoint-initdb.d"
      - type: volume
        source: mpower-db-volume
        target: /var/lib/mysql
    container_name: mpower-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: $CPRO_DATABASE_NAME
      MYSQL_USER: $CPRO_DATABASE_USER
      MYSQL_PASSWORD: $CPRO_DATABASE_PASSWORD
    networks:
      - tbapi

  tbapp-db:
    env_file: ${SHARED_ENV_FILE}
    restart: always
    image: mysql:5.7
    hostname: tbapp-db
    volumes:
      - "./db/sql/tbapp-db:/docker-entrypoint-initdb.d"
      - type: volume
        source: tbapp-db-volume
        target: /var/lib/mysql
    # ports:
    #   - "3307:3306"
    container_name: tbapp-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: $TB_DATABASE_NAME
      MYSQL_USER: $TB_DATABASE_USER
      MYSQL_PASSWORD: $TB_DATABASE_PASSWORD
    networks:
      - tbapi

volumes:
  web:
  mpower-db-volume:
  tbapp-db-volume:

networks:
  tbapi:
