version: '3.3'
services:
  client: 
    restart: always
    ports:
      - "8082:3000"
    build:
      context: https://github.com/uwcirg/tb-mobile-app.git#feature/docker-compose-cpro
    # volumes:
    #   - ".:/usr/src/app"
    stdin_open: true
    tty: true
    container_name: tb-mobile-app  
    command: yarn install && yarn start
  web:
    restart: always
    build:
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - target: 5000
        published: ${API_EXTERNAL_PORT:-5060}
    volumes:
      - "web:/usr/src/app"
    links:
      - mpower-db
      - tbapp-db
    container_name: tb-api
    stdin_open: true
    #command: /usr/local/bin/gunicorn -w 2 -b :8000 project:app
    command: /wait && /usr/local/bin/gunicorn -w 2 -b :8000 project:app
    
    tty: true
    depends_on:
      - mpower-db
      - tbapp-db
    environment:
      WAIT_HOSTS: mpower-db:3306, tbapp-db:3306
      WAIT_BEFORE_HOSTS: 10
      #FLASK_APP: "tbapi.factory:create_app()"
      FLASK_APP: "tbapi_app.py"
      FLASK_DEBUG: 1
      AUTHLIB_INSECURE_TRANSPORT: 'true'
      MODE: 'dev'
    networks:
      - tbapi

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "8081:80"
    volumes:
      - web:/www/static
    depends_on:
      - web
    networks:
      - tbapi
  mpower-db:
    restart: always
    image: mysql:5.7
    hostname: mpower-db
    volumes:
      - "./db/sql/mpower-db:/docker-entrypoint-initdb.d"
      - type: volume
        source: mpower-db-volume
        target: /var/lib/mysql
    # ports:
    #   - "3306:3306"
    container_name: mpower-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mpower_demo
      MYSQL_USER: mpower
      MYSQL_PASSWORD: mpower
    networks:
      - tbapi

  tbapp-db:
    restart: always
    image: mysql:5.7
    hostname: tbapp-db
    volumes:
      - "./db/sql/tbapp-db:/docker-entrypoint-initdb.d"
      - type: volume
        source: tbapp-db-volume
        target: /var/lib/mysql
    # ports:
    #   - "3307:3306"
    container_name: tbapp-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tbapi
      MYSQL_USER: tbapi
      MYSQL_PASSWORD: tbapi
    networks:
      - tbapi

volumes:
  web:
  mpower-db-volume:
  tbapp-db-volume:

networks:
  tbapi:
